# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LF1kiSjHK68xaVoQTYM_auH8o4VVzyuo
"""

class Management:
  def __init__(self):
    self.doctor_manager = DoctorManager()
    self.patient_manager = PatientManager()

  def display_menu(self):
    while True:
      options= input('\nWelcome to Alberta Hospital (AH) MAnager Systems\n1 - Doctors\n2 - Patients\n3 - Exit Program\n>>>')
      if options  == '1':
        self.doctors_menu()
      elif options == '2':
        self.patients_menu()
      elif options == '3':
        print('Thanks for using the program. Bye!')
      else:
        print('Invalid choice. Please try again.')

  def doctors_menu(self):
    while True:
      options= input('\nDoctors Menu:\n1 - Display Doctors list\n2 - Search for doctor by ID\n3 - Search for doctor by name\n4 - Add doctor\n5 - Edit doctor info\n6 - Back to the main menu\n>>>')
      if options == '1':
        self.doctor_manager.display_doctors_list()
      elif options == '2':
        doctor_id = input('Enter doctor ID: ')
        self.doctor_manager.search_doctor_by_id(doctor_id)
      elif options == '3':
        doctor_name = input('Enter doctor name: ')
        self.doctor_manager.search_doctor_by_name(doctor_name)
      elif options == '4':
        self.doctor_manager.add_dr_to_file()
      elif options == '5':
        doctor_id = input('Enter doctor ID you want to edit: ')
        self.doctor_manager.edit_doctor_info()
      elif options == '6':
        break
      else:
        print('Invalid choice. Please try again.')

  def patients_menu(self):
    while True:
      options= input('\nPatients Menu:\n1 - Display Patients list\n2 - Search for patient by ID\n3 - Add patient\n4 - Edit patient info\n5 - Back to the main menu\n>>>')
      if options == '1':
        self.patient_manager.display_patients_list()
      elif options == '2':
        patient_id = input('Enter patient ID: ')
        self.patient_manager.search_patient_by_id(patient_id)
      elif options == '3':
        self.patient_manager.add_patient_to_file()
      elif options == '4':
        patient_id = input('Enter patient ID you want to edit: ')
        self.patient_manager.edit_patient_info_by_id()
      elif options == '5':
        break
      else:
        print('Invalid choice. Please try again.')

if __name__ == '__main__':
  management = Management()
  management.display_menu()