# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXe4xd7pnMgmkxsh3B9CkaTvCcY-s4-g
"""

class Doctor():
    def __init__(self):
        self.id = ''
        self.name = ''
        self.specialization = ''
        self.working_time = ''
        self.qualifications = ''
        self.room_number = ''

    def get_doctor_id(self):
        return self.id
    def get_doctor_name(self):
        return self.name
    def get_doctor_specialize(self):
        return self.specialization
    def get_doctor_work_time(self):
        return self.working_time
    def get_doctor_qualify(self):
        return self.qualifications
    def get_doctor_room_number(self):
        return self.room_number

    def set_doctor_id(self, new_id):
        self.id = new_id
    def set_doctor_name(self, new_name):
        self.name = new_name
    def set_doctor_specialize(self, new_specialization):
        self.specialization = new_specialization
    def set_doctor_work_time(self, new_work_time):
        self.working_time = new_work_time
    def set_doctor_qualify(self, new_qualifications):
        self.qualifications = new_qualifications
    def set_doctor_room_number(self, new_room_number):
        self.room_number = new_room_number
    def __str__(self):
        return f"{self.id}_{self.name}_{self.specialization}_{self.working_time}_{self.qualifications}_{self.room_number}"


class Patient:
  def __init__(self):
    self.id = 0
    self.name = ""
    self.disease = ""
    self.gender = ""
    self.age = 0

  # getters
  def get_id(self) -> int:
    return self.id

  def get_name(self) -> str:
    return self.name

  def get_disease(self) -> str:
    return self.disease

  def get_gender(self) -> str:
    return self.gender

  def get_age(self) -> int:
    return self.age

  # setters
  def set_id(self, id: int):
    self.id = id

  def set_name(self, name: str):
    self.name = name

  def set_disease(self, disease: str):
    self.disease = disease

  def set_gender(self, gender: str):
    self.gender = gender

  def set_age(self, age: int):
    self.age = age

  def __str__(self):
    return f"{self.id}_{self.name}_{self.disease}_{self.gender}_{self.age}"